version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-frontend
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/frontend
      - /frontend/node_modules
