# Generated by Django 5.0.1 on 2024-01-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_at']},
        ),
    ]
