# Generated by Django 5.0.1 on 2024-01-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='like',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
